root = "."
tmp_dir = "tmp"

[build]
    bin = "./tmp/main"
    cmd = "go build -o {{.Output}} {{.Input}}"
    exclude_dir = ["node_modules", "frontend/node_modules"]
    include_ext = ["go", "tpl", "tmpl"]
    exclude_ext = ["go.mod", "go.sum"]
    ignore = ["tmp/*"]

[dirs]
    watch = ["."]
    exclude = ["node_modules", "frontend/node_modules"]