root = "."
tmp_dir = "tmp"

[build]
    bin = "tmp/main.exe"
    cmd = "go build -o ./tmp/main.exe"
    exclude_dir = ["./node_modules", "frontend"]
    include_ext = ["go", "tpl", "tmpl"]
    exclude_ext = ["go.mod", "go.sum"]
    ignore = ["tmp/*", "frontend"]

[dirs]
    watch = ["."]
    exclude = ["./node_modules", "frontend"]