import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Navbar from "@/components/Navbar";
import "./globals.css";
import SideBar from "@/components/SideBar";
import ReduxProvider from "./redux-provider";
import { UserProvider } from "./user-provider";

const poppins = Roboto({ 
    subsets: ["latin"],
    display: "swap",
    variable: "--font-poppins",
    weight: ["100", "300", "400", "500", "700", "900"]
 });

export const metadata: Metadata = {
    title: "Bookle",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`min-h-screen `} 
        // style={{
        //     backgroundImage: `url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32' width='32' height='32' fill='none' stroke-width='2' stroke='%2318181b'%3e%3cpath d='M0 .5H31.5V32'/%3e%3c/svg%3e")`,
        //   }}
          >
            <div className="">
                <body className={`bg-[#D7A449]/50 backdrop-blur-md lg:flex flex-row gap-6 px-4 lg:px-0  ${poppins.className}`}>
                    <ReduxProvider>
                        <UserProvider />
                        <div className="hidden lg:block w-[15%]">
                            <SideBar />
                        </div>
                        <div className=" lg:w-[85%]">
                            <Navbar />
                            {children}
                        </div>
                    </ReduxProvider>
                </body>
            </div>
        </html>
    );
}
