import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Navbar from "@/components/Navbar";
import "./globals.css";
import SideBar from "@/components/SideBar";
import ReduxProvider from "./redux-provider";
import UserBadge from "@/components/UserBadge";
// import { fetchUser } from "./user-provider";
import { Toaster } from "sonner";
import { getUser } from "@/lib/getUser";

const poppins = Roboto({ 
    subsets: ["latin"],
    display: "swap",
    variable: "--font-poppins",
    weight: ["100", "300", "400", "500", "700", "900"]
 });

export const metadata: Metadata = {
    title: "Bookle",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    // const user = await fetchUser()
    const user = await getUser()
    console.log(user)
    return (
        <html lang="en" className={` `} 
        // style={{
        //     backgroundImage: `url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32' width='32' height='32' fill='none' stroke-width='2' stroke='%2318181b'%3e%3cpath d='M0 .5H31.5V32'/%3e%3c/svg%3e")`,
        //   }}
          >
            <div className="">
                <body className={`bg-[#D7A449]/30 backdrop-blur-md lg:flex flex-row gap-6 px-4 lg:px-0 w-full ${poppins.className}`}>
                    <ReduxProvider>
                        <Toaster />
                        <div className="grid grid-cols-12 ">
                            <div className="hidden op-50% left-50  col-span-4">
                                {/* <UserBadge  /> */}
                                <SideBar data={user} />
                            </div>
                            <div className="min-h-screen max-w-6xl mx-auto md:px-8 lg:col-span-8">
                                <Navbar />
                                {children}
                            </div>
                        </div>
                    </ReduxProvider>
                </body>
            </div>
        </html>
    );
}
